/*
 * generated by Xtext 2.15.0
 */
package com.truneo.hdl.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class HDLEditor extends XbaseEditor {
}
