/*
 * generated by Xtext 2.15.0
 */
package com.truneo.hdl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractHDLScopeProvider extends XbaseBatchScopeProvider {
}
