/*
 * generated by Xtext 2.15.0
 */
package com.truneo.hdl.ui;

import com.google.inject.Injector;
import com.truneo.hdl.ui.internal.HdlActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HdlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HdlActivator activator = HdlActivator.getInstance();
		return activator != null ? activator.getInjector(HdlActivator.COM_TRUNEO_HDL_HDL) : null;
	}

}
