/*
 * generated by Xtext 2.15.0
 */
package com.truneo.hdl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class HDLRuntimeModule extends AbstractHDLRuntimeModule {

    override Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
        com.truneo.hdl.jvmmodel.DomainmodelGenerator
    }
}
