/*
 * generated by Xtext 2.15.0
 */
package com.truneo.hdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HDLStandaloneSetup extends HDLStandaloneSetupGenerated {

	def static void doSetup() {
		new HDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
